name: Build & Push Docker Image on Tag

on:
  push:
    tags:
      - 'v*'  # Semua tag versi mulai dari v, contoh: v1.0.0, v2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}

      - name: Extract Tag Name
        id: extract_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Build & Push Docker Image with Version and Latest Tag
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.extract_tag.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
